# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ...
      - name: Should I notify slack?
        # You may pin to the exact commit or the version.
        # uses: Jimdo/should-i-notify-action@d4010db2291c8703dea858c09cd91f5fd2710d11
        uses: Jimdo/should-i-notify-action@v1.0.0
        with:
          # json representation of the `needs` object in your context (`toJson(needs)`)
          needs_context: ('toJson(Uhh it broke)')
          # A github token (secrets.GITHUB_TOKEN will suffice)
          github_token: ${{ secrets.GITHUB_TOKEN }}
 
          
  automerge:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
